#include "DBoW3/DBoW3.h"
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/features2d/features2d.hpp>
#include <iostream>
#include <vector>
#include <string>

using namespace cv;
using namespace std;

/***************************************************
 * 本节演示了如何根据前面训练的字典计算相似性评分
 * ************************************************/
int main(int argc, char **argv) {
    // read the images and database  
    cout << "reading database" << endl;
    DBoW3::Vocabulary vocab("../vocabulary.yml.gz");
    // DBoW3::Vocabulary vocab("../vocab_larger.yml.gz");  // use large vocab if you want: 
    if (vocab.empty()) {
        cerr << "Vocabulary does not exist." << endl;
        return 1;
    }
    cout << "reading images... " << endl;
    vector<Mat> images;
    for (int i = 0; i < 10; i++) {
        string path = "../data/" + to_string(i + 1) + ".png";
        images.push_back(imread(path));
    }

    // NOTE: in this case we are comparing images with a vocabulary generated by themselves, this may lead to overfit.
    // detect ORB features
    cout << "detecting ORB features ... " << endl;
    Ptr<Feature2D> detector = ORB::create();
    vector<Mat> descriptors;
    for (Mat &image:images) {
        vector<KeyPoint> keypoints;
        Mat descriptor;
        detector->detectAndCompute(image, Mat(), keypoints, descriptor);
        descriptors.push_back(descriptor);
    }

    // we can compare the images directly or we can compare one image to a database 
    // images :
    cout << "comparing images with images " << endl;
    for (int i = 0; i < images.size(); i++) {
        DBoW3::BowVector v1; // map<word_id, word_weight>
        vocab.transform(descriptors[i], v1);
        for (int j = i; j < images.size(); j++) {
            DBoW3::BowVector v2;
            vocab.transform(descriptors[j], v2);
            double score = vocab.score(v1, v2);
            cout << "image " << i << " vs image " << j << " : " << score << endl;
        }
        cout << endl;
    }

    // or with database 
    cout << "comparing images with database " << endl;
    DBoW3::Database db(vocab, false, 0);
    for (int i = 0; i < descriptors.size(); i++)
        db.add(descriptors[i]);
    cout << "database info: " << db << endl;
    for (int i = 0; i < descriptors.size(); i++) {
        DBoW3::QueryResults ret;
        db.query(descriptors[i], ret, 4);      // max result=4
        cout << "searching for image " << i << " returns " << ret << endl << endl;
    }


    // 输出相似度矩阵（使用 DBoW3 的 score）
    cout << "\n========================================" << endl;
    cout << "Similarity matrix:" << endl;
    cout << "========================================" << endl;
    
    // 先保存所有 BowVector
    vector<DBoW3::BowVector> all_bow_vectors;
    for (int i = 0; i < descriptors.size(); i++) {
        DBoW3::BowVector v;
        vocab.transform(descriptors[i], v);
        all_bow_vectors.push_back(v);
    }
    
    // 打印列标题
    cout << "     ";
    for (int j = 0; j < all_bow_vectors.size(); j++) {
        cout << "  img" << j << "  ";
    }
    cout << endl;
    
    // 打印矩阵内容
    for (int i = 0; i < all_bow_vectors.size(); i++) {
        cout << "img" << i << " ";
        for (int j = 0; j < all_bow_vectors.size(); j++) {
            double score = vocab.score(all_bow_vectors[i], all_bow_vectors[j]);
            printf(" %6.4f ", score);
        }
        cout << endl;
    }

    /*
    ========================================
    Similarity matrix:
    ========================================
        img0    img1    img2    img3    img4    img5    img6    img7    img8    img9  
    img0  1.0000  0.0195  0.0152  0.0227  0.0139  0.0243  0.0230  0.0165  0.0105  0.0357 
    img1  0.0195  1.0000  0.0365  0.0260  0.0158  0.0160  0.0174  0.0158  0.0160  0.0180 
    img2  0.0152  0.0365  1.0000  0.0217  0.0221  0.0219  0.0224  0.0179  0.0197  0.0147 
    img3  0.0227  0.0260  0.0217  1.0000  0.0248  0.0278  0.0308  0.0255  0.0221  0.0226 
    img4  0.0139  0.0158  0.0221  0.0248  1.0000  0.0355  0.0206  0.0195  0.0239  0.0120 
    img5  0.0243  0.0160  0.0219  0.0278  0.0355  1.0000  0.0279  0.0237  0.0164  0.0208 
    img6  0.0230  0.0174  0.0224  0.0308  0.0206  0.0279  1.0000  0.0284  0.0218  0.0265 
    img7  0.0165  0.0158  0.0179  0.0255  0.0195  0.0237  0.0284  1.0000  0.0102  0.0189 
    img8  0.0105  0.0160  0.0197  0.0221  0.0239  0.0164  0.0218  0.0102  1.0000  0.0157 
    img9  0.0357  0.0180  0.0147  0.0226  0.0120  0.0208  0.0265  0.0189  0.0157  1.0000 
     */


    cout << "done." << endl;
}